border_width = 7
margin = 2
workspace_margin = 4
# default_width = 1280
# default_height = 720
# always_float = false
# default_border_color = "#bd93f9"
default_border_color = "#512b87"
floating_border_color = "#bd93f9"
focused_border_color = "#ff79c6"
